spring.application.name=notification-service
server.port=8086
server.servlet.context-path=/notification
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
#db
spring.mongodb.host=localhost
spring.mongodb.port=27020
spring.mongodb.database=notification-db
spring.mongodb.username=root
spring.mongodb.password=hienhien123@
spring.mongodb.authentication-database=admin
#java mail
mail.sender.username=clonejavamail@gmail.com
mail.sender.password=sjws mzks xchh dnpb