spring.application.name=identity-service
server.port=8080
server.servlet.context-path=/identity
eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://identity-service-db:3306/dihitube-identity-db
spring.datasource.username=root
spring.datasource.password=hienhien123@

#TTL
security.jwt.access.timeout=300
#minute
security.jwt.refresh.timeout=30
#day
security.jwt.reset.timeout=15
#minute
# jwt secret key
security.jwt.access.secretKey=ZXdyd2Vyd3Jld3Jld3Jld2ZzZGZzZGZyNTY0NjU0NTQ2NTQ2NTQ2MzI0MjM0
security.jwt.refresh.secretKey=b2V1cmFtc2RrZmV3aHJlaXdyZXdvcixtc2Q0ODIzNDkyNDQ5NDgwMjU4OTQ=
security.jwt.reset.secretKey=b2V1cmFtc2RrZmV3aHJlaXdyZXdvcixtc2Q0ODIzNDkyNDQ5NDgwMjU4OTQ=

#kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=user-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.admin.auto-create=true
#logging.level.org.apache.kafka=DEBUG
logging.level.org.apache.kafka=INFO
logging.level.org.springframework.kafka=INFO