spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-service
              uri: lb://identity-service
              predicates:
                - Path=/identity/**
            - id: metadata-service
              uri: lb://metadata-service
              predicates:
                - Path=/metadata/**
            - id: profile-service
              uri: lb://profile-service
              predicates:
                - Path=/profile/**
            - id: file-service
              uri: lb://file-service
              predicates:
                - Path=/file/external/**
            - id: search-service
              uri: lb://search-service
              predicates:
                - Path=/search/external/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: true
server:
  port: 8888
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
    level.reactor.netty.http.client: DEBUG
    level.org.springframework.web.reactive.function.client: DEBUG
    level.org.springframework.cloud.loadbalancer=DEBUG: