spring.application.name=file-service
server.port=8083
server.servlet.context-path=/file
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
#db
spring.mongodb.host=localhost
spring.mongodb.port=27020
spring.mongodb.database=file-db
spring.mongodb.username=root
spring.mongodb.password=hienhien123@
spring.mongodb.authentication-database=admin
#minio config
minio.url=http://localhost:9000
minio.access-key=admin
minio.secret-key=hienhien123@
minio.images.bucket=images
minio.videos.bucket=videos
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB